### ISSUE TITLE
Transaction apparently doesn't show up right amount

### ISSUE THREAD

**Issue by mrandika** [Wisnu-C23-PS427/wisnu-backend#10]
Description:
After creating new transaction, the data doesn't show up right amount in either ticket or order endpoint. According to last issue #9, the order is created at 16:35:49.

![Screenshot 2023-06-14 at 23 52 56](https://github.com/Wisnu-C23-PS427/wisnu-backend/assets/19660992/35b3dd76-6848-40d4-a862-dd7c66f9fc37)

**Comment by adiyatmapw** [comment]
ticket has connected to database /transactions
